# Generated by Django 3.0.6 on 2020-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankNames',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Bank_Names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('adr1', models.TextField(blank=True, null=True)),
                ('adr2', models.TextField(blank=True, null=True)),
                ('adr3', models.TextField(blank=True, null=True)),
                ('adr4', models.TextField(blank=True, null=True)),
                ('adr5', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('micr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Data',
                'managed': False,
            },
        ),
    ]
