# Generated by Django 3.0.6 on 2020-07-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
    ]
